// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpqfvhgzppadgbirdxtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcWZ2aGd6cHBhZGdiaXJkeHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTcyOTksImV4cCI6MjA2Nzg3MzI5OX0.8snhB5Mev0uxRv7sfBWiRocbsTq3l6G-bOlmbkjdG2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});